### ISSUE TITLE
Mono.Debugging.Soft.SoftDebuggerSession.LoadPdbFile NullReferenceException

### ISSUE THREAD

**Issue by ezverev** [mono/debugger-libs#190]
When mono.exe is launched without the mdb-optimizations option the IDE extension fails in Mono.Debugging.Soft.SoftDebuggerSession.LoadPdbFile

sample command for issue repro:
"C:\Program Files (x86)\Mono\bin\mono.exe" --debug --debugger-agent=transport=dt_socket,address=127.0.0.1:8874 "C:\develop\User\Prototypes\MonoSampleProject1\bin\Debug\MonoSampleProject1.exe"

sample command which works ok:
"C:\Program Files (x86)\Mono\bin\mono.exe" --debug=mdb-optimizations --debugger-agent=transport=dt_socket,address=127.0.0.1:8874 "C:\develop\User\Prototypes\MonoSampleProject1\bin\Debug\MonoSampleProject1.exe"

```
EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Mono.Debugging.Soft.SoftDebuggerSession.LoadPdbFile(String assemblyFileName, String pdbFileName)
   at Mono.Debugging.Soft.SoftDebuggerSession.LoadDebugFile(String assemblyFileName, String debugFileName, Func`3 loadDebugFile)
   at Mono.Debugging.Soft.SoftDebuggerSession.CheckBetterMatch(TypeMirror type, String file, Int32 line, Int32 column, Location found)
   at Mono.Debugging.Soft.SoftDebuggerSession.FindLocationByMethod(MethodMirror method, String file, Int32 line, Int32 column, Boolean& insideTypeRange)
   at Mono.Debugging.Soft.SoftDebuggerSession.FindLocationByType(TypeMirror type, String file, Int32 line, Int32 column, Boolean& genericMethod, Boolean& insideTypeRange)
   at Mono.Debugging.Soft.SoftDebuggerSession.ResolveBreakpoints(TypeMirror type)
   at Mono.Debugging.Soft.SoftDebuggerSession.HandleTypeLoadEvents(TypeLoadEvent[] events)
   at Mono.Debugging.Soft.SoftDebuggerSession.HandleEventSet(EventSet es)
   at Mono.Debugging.Soft.SoftDebuggerSession.EventHandler()
```

**Comment by jstedfast** [comment]
we no longer load these files in the SoftDebuggerSession, so this is no longer an issue.
