### ISSUE TITLE
System.ArgumentException:  An item with the same key has already been added.

### ISSUE THREAD

**Issue by MagicAndre1981** [mono/debugger-libs#192]
While trying to debug an Xamarin Android app in VS2017, 15.8 Preview 5, I got this exception:

```
EXCEPTION: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Mono.Debugging.Soft.SoftDebuggerSession.RegisterAssembly(AssemblyMirror asm) in E:\A\_work\102\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1914
   at Mono.Debugging.Soft.SoftDebuggerSession.ProcessType(TypeMirror t) in E:\A\_work\102\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2395
   at Mono.Debugging.Soft.SoftDebuggerSession.OnInsertBreakEvent(BreakEvent breakEvent) in E:\A\_work\102\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 978
   at Mono.Debugging.Client.DebuggerSession.AddBreakEvent(BreakEvent be) in E:\A\_work\102\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Client\DebuggerSession.cs:line 624
```

![grafik](https://user-images.githubusercontent.com/8274816/43882464-03faae40-9bb0-11e8-8c35-071d8afc669a.png)

----------------------

Version information:

Microsoft Visual Studio Enterprise 2017 Preview
Version 15.8.0 Preview 5.0
VisualStudio.15.Preview/**15.8.0-pre.5.0**+27924.0
Microsoft .NET Framework
Version 4.7.03062

Mono Debugging for Visual Studio   4.11.7-pre (8955b2a)
Support for debugging Mono processes with Visual Studio.

Xamarin   4.11.0.731 (d15-8@1b61b3b4e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.14.218 (79f535bdd)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.104 (12ebed1)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.17 (HEAD/dfb09269d)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.14.0.11 (61d20a8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by joj** [comment]
Hi @MagicAndre1981, can you post this in developer community? It will get more eyes there. Also, if possible, I would need to see either the csproj that's resulting in that or a detailed build output. That depends on how private that is, of course. You can attach privately in developer community if needed.

Thanks,
J

**Comment by MagicAndre1981** [comment]
@joj 

I haven't seen it for a while, but today I got it again with VS2017 15.9.11 and same callstack. I don't have a repro, it happens very rarely.

**Comment by jstedfast** [comment]
This used to be a dictionary of some kind, but isn't anymore which should have fixed this issue.
